### PR TITLE
Support more ways to build with dependency to collada-dom library

### PR DESCRIPTION
**Pull request by elsid**
1. Add more paths to find collada library. Existing onces ignore the default install location defined [here](https://github.com/rdiankov/collada-dom/blob/c1e20b7d6ff806237030fe82f126cb86d661f063/CMakeLists.txt#L141).
2. Find collada dependencies only when found static library. If it's only dynamic library, all dependencies are linked to it and there is no need to find them. Attempt to do so may fail because of locations mismatch. `CMakeModules/FindCOLLADA.cmake` supports only very specific locations for them.

I've tried to create similar [pull request](https://github.com/openscenegraph/OpenSceneGraph/pull/1138) for OpenSceneGraph but it's being ignored.

### CODE REVIEW

**Comment by AnyOldName3** [comment]
Have you asked Psi to chase up Robert about the original PR? If not, doing so might be enough to get it taken seriously.

**Comment by elsid** [comment]
Nope. If PR doesn't look serious, I'd expect it to be closed or to have a comment about what's wrong. Relying on personal communication channels is not my way.

**Comment by psi29a** [comment]
I'll take it up then.

**Comment by psi29a** [comment]
Because I patched this a long time ago here: https://gitlab.com/OpenMW/openmw-dep/-/blob/main/macos/osg.patch

**Pull request merged**
