### PR TITLE
Support BC4- and BC5-compressed DDS images

### PR DESCRIPTION
**Pull request by Capostrophic**
Think I got the formats right. Upstream is still dead atm.

### CODE REVIEW

**Comment by AnyOldName3** [comment]
This is only a subset of BC4 and BC5 DDSes. Most I've seen in the wild set the FourCC to `DX10` and then set the format via the optional DX10 header.

**Comment by Capostrophic** [comment]
Well I specifically target Fallout 4 in this one. :stuck_out_tongue:

**Comment by AnyOldName3** [comment]
Fallout 4 doesn't have DDS files. It has the data *from* the DDS files chopped up in texture BA2s. It's down to the specific BA2 decompressor whether it emits FourCCs or a DX10 header because it's creating them from scratch.

**Comment by Capostrophic** [comment]
Should cover more things now, hopefully.

**Comment by AnyOldName3** [comment]
Looks reasonable. Is the y mirroring implemented for these two formats already in OSG? IIRC, they're doable.

**Comment by Capostrophic** [comment]
Unfortunately, flipping is only implemented for DXT1/3/5. Basically, whatever limited support was there for ATI1/ATI2 since 2010 is extended to BC4/BC5.


I'll try to tinker with that later (OSG will happily corrupt the image by using normal v-flip at the moment, which was a horrible idea on Robert's side), but this at least covers the DDS part. Actually, this is probably a blocker for the whole thing.

**Comment by Capostrophic** [comment]
This now adds vertical flipping support to affected pixel formats. That's the easy part, and technically provides everything I had in mind for this.

~~Cursed~~ 2017 additions of software decompression and reorientation for S3TC are the vaguely difficult part I'm kind of unwilling to tackle (i.e. adapt to RGTC).

**Review by AnyOldName3 — APPROVED** [review]

**Pull request merged**
